### PR TITLE
add temporary hyprland backend

### PR DESCRIPTION
**Pull request by jacekpoz**
to be removed when https://github.com/hyprwm/Hyprland/pull/3544 is merged

wiki note: https://wiki.hyprland.org/Configuring/Monitors/#rotating

### CODE REVIEW

**Comment by Smona** [comment]
@jacekpoz nice work on the change, but I have just been able to confirm that https://github.com/hyprwm/Hyprland/pull/3544 is now in working condition! Maybe you can give that commit a try (along with the [config to make it work](https://github.com/hyprwm/Hyprland/pull/3544#issuecomment-1960931732))? If it works for you too it may be best to close this PR.

**Comment by jacekpoz** [comment]
I haven't tried that yet, I think it's a good idea to have this temporarily before that PR is merged - unless it's gonna get merged soon

**Comment by jacekpoz** [comment]
tested `f52580717e65d86dafd9cf458e15919950e0625a`, didn't work with no config changes and upstream rot8

not sure if any config changes are needed, will try again today in the evening / tomorrow and read through all the comments and code

if there's any config needed please let me know, I'll retest

**Comment by Smona** [comment]
I had to explicitly map touch inputs to my output name, like this:

```
input {
    touchdevice {
        output = eDP-1
    }
    tablet {
        output = eDP-1
    }
}
```

**Comment by jacekpoz** [comment]
sorry for the long response, that config does in fact work

closing, supported natively in hyprland now

**Pull request closed without merging**
