### PR TITLE
Add hook functionality

### LINKED ISSUE #4: Screen rotation hooks for custom commands
Opening this issue to get feedback, how would you feel about adding a way to configure custom commands to run after a screen rotation event?

My use case is that I need to restart [waybar](https://github.com/Alexays/Waybar/) after rotation for it to resize to fit the new output dimensions. I could write a custom script to watch the accelerometer status but it feels like it would be very duplicative of the logic already defined in this project.

I think my ideal would be to add an optional config file that would include a list of commands to execute after a rotation event is detected. What do you think?

### PR DESCRIPTION
**Pull request by juliag2**
Add hook functionality, as requested in #4. Use $ORIENTATION in custom scripts. $ORIENTATION can be any of "normal", "90", "180" and "270".

This adds two hook arguments, one "--hooks", which executes after the screen has rotated, and "--beforehooks", which executes before any changes are made. These are both comma-seperated.

Closes #4.

### CODE REVIEW

**Comment by juliag2** [comment]
Added $PREV_ORIENTATION for scripts requiring knowledge of the previous orientation.

**Comment by efernau** [comment]
Hey, @juliag2  thanks for the pullrequest, unfortunately one of the checks was not successful (rustfmt). 
Any idea why? I dont have time to check this right now.

```
/home/runner/.cargo/bin/cargo fmt --all -- --check
Diff in /home/runner/work/rot8/rot8/src/main.rs at line 255:
     let display = matches.value_of("display").unwrap_or("default.conf");
     let touchscreens: Vec<&str> = matches.values_of("touchscreen").unwrap().collect();
     let hooks: Vec<&str> = matches.values_of("hooks").unwrap_or_default().collect();
-    let beforehooks: Vec<&str> = matches.values_of("beforehooks").unwrap_or_default().collect();
+    let beforehooks: Vec<&str> = matches
+        .values_of("beforehooks")
+        .unwrap_or_default()
+        .collect();
     let disable_keyboard = matches.is_present("keyboard");
     let threshold = matches.value_of("threshold").unwrap_or("default.conf");
     let old_state_owned = get_window_server_rotation_state(display, &backend)?;
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1
```

**Comment by raptor8134** [comment]
It wants you to expand 
```
let beforehooks: Vec<&str> = matches.values_of("beforehooks").unwrap_or_default().collect();
``` 
into
```
let beforehooks: Vec<&str> = matches
.values_of("beforehooks")
.unwrap_or_default()
.collect();
```
I don't want to make a branch+pr just for that lol

**Comment by juliag2** [comment]
There, this should do it. I don't do a lot of coding anymore so apologies this took so long.

**Comment by efernau** [comment]
hey @juliag2
awesome, thank you for your time
rustfmt does not want, can you look again?

**Comment by juliag2** [comment]
@efernau already done, I think it's just really strict on when to expand lines.

**Comment by efernau** [comment]
thanks, merged...

**Pull request merged**
