### PR TITLE
Add simple transformation flags

### PR DESCRIPTION
**Pull request by sidju**
Solves edge cases where accelerometers orientation doesn't match display

In essence this is for the pinephone, but simpler than the changes suggested by Dejvino. I still think file selection could be beneficial if you need to combine accelerometers, but this is a simple solution for the most common orientation problem.

### CODE REVIEW

**Comment by sidju** [comment]
Easiest way is to git clone the fork to your phone and run
`cargo install -d .` in the folder (also add ~/.cargo/bin to your PATH, as required for cargo install). Before installation you might wish to verify that it works though, best done by just running `cargo run --release` in the folder.

**Comment by ragreenburg** [comment]
Sorry for the delayed response here. I tried this last night and unfortunately it didn't work. The steps I did was kill rot8, which was already running on my machine with `killall rot8`. I ran it a few times just to make sure it was killed. Then I ran `cargo run --release -- --display DSI-1 --threshold 0.97`. When I have the phone in landscape it works just fine but in portrait it is off by 180 degrees.

**Comment by sidju** [comment]
Yes. As you can see in the files changed this isn't a specific patch for the pinephone but instead an addition of transformation flags to correct how the coordinates are interpreted. Try flipping some of the axis around and mapping them around using those flags.

(I think I did something like switch x and y and invert y, but I am not sure. Test around.)

**Comment by ragreenburg** [comment]
Shoot, you are right. I clearly didn't read this correctly. Good news, it works! I ran it with `rot8 --display DSI-1 --threshold 0.97 --invert-y` and it fixed the issue!

**Comment by efernau** [comment]
@sidju thanks for implementing this, i think it works well.

**Pull request merged**
